

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 830)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("font: 75 14pt \"Comic Sans MS\";")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 10, 151, 31))
        self.label.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 50, 1001, 751))
        self.textBrowser.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.textBrowser.setUndoRedoEnabled(False)
        self.textBrowser.setObjectName("textBrowser")
        self.A = QtWidgets.QLabel(self.centralwidget)
        self.A.setGeometry(QtCore.QRect(100, 370, 31, 21))
        self.A.setObjectName("A")
        self.B = QtWidgets.QLabel(self.centralwidget)
        self.B.setGeometry(QtCore.QRect(100, 430, 31, 21))
        self.B.setObjectName("B")
        self.D = QtWidgets.QLabel(self.centralwidget)
        self.D.setGeometry(QtCore.QRect(100, 550, 31, 21))
        self.D.setObjectName("D")
        self.C = QtWidgets.QLabel(self.centralwidget)
        self.C.setGeometry(QtCore.QRect(100, 490, 31, 21))
        self.C.setObjectName("C")
        self.option1 = QtWidgets.QRadioButton(self.centralwidget)
        self.option1.setGeometry(QtCore.QRect(130, 360, 471, 41))
        self.option1.setObjectName("option1")
        self.option2 = QtWidgets.QRadioButton(self.centralwidget)
        self.option2.setGeometry(QtCore.QRect(130, 420, 471, 41))
        self.option2.setObjectName("option2")
        self.option3 = QtWidgets.QRadioButton(self.centralwidget)
        self.option3.setGeometry(QtCore.QRect(130, 480, 471, 41))
        self.option3.setObjectName("option3")
        self.option4 = QtWidgets.QRadioButton(self.centralwidget)
        self.option4.setGeometry(QtCore.QRect(130, 540, 471, 41))
        self.option4.setObjectName("option4")
        self.answer = QtWidgets.QPushButton(self.centralwidget)
        self.answer.setGeometry(QtCore.QRect(130, 600, 161, 51))
        self.answer.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.answer.setObjectName("answer")
        self.question = QtWidgets.QLabel(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(10, 240, 991, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.question.sizePolicy().hasHeightForWidth())
        self.question.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.question.setFont(font)
        self.question.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.question.setObjectName("question")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 150, 261, 61))
        self.label_7.setObjectName("label_7")
        self.sport_button = QtWidgets.QPushButton(self.centralwidget)
        self.sport_button.setGeometry(QtCore.QRect(300, 160, 161, 51))
        self.sport_button.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.sport_button.setObjectName("sport")
        self.history_button = QtWidgets.QPushButton(self.centralwidget)
        self.history_button.setGeometry(QtCore.QRect(700, 160, 161, 51))
        self.history_button.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.history_button.setObjectName("history")
        self.literature_button = QtWidgets.QPushButton(self.centralwidget)
        self.literature_button.setGeometry(QtCore.QRect(500, 160, 161, 51))
        self.literature_button.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.literature_button.setObjectName("literature")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "QUESTION 1"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans MS\'; font-size:14pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.A.setText(_translate("MainWindow", "A )"))
        self.B.setText(_translate("MainWindow", "B )"))
        self.D.setText(_translate("MainWindow", "D )"))
        self.C.setText(_translate("MainWindow", "C )"))
        self.option1.setText(_translate("MainWindow", "TOLSTOY"))
        self.option2.setText(_translate("MainWindow", "DOSTOYEVSKI"))
        self.option3.setText(_translate("MainWindow", "GEORGE ORWELL"))
        self.option4.setText(_translate("MainWindow", "STEFAN ZWEIG"))
        self.answer.setText(_translate("MainWindow", "ANSWER"))
        self.question.setText(_translate("MainWindow", "AŞAĞIDAKİLERDEN HANGİSİ \'HAYVAN ÇİFTLİĞİ\' KİTABININ YAZARIDIR?"))
        self.label_7.setText(_translate("MainWindow", "PLEASE SELECT CATEGORY"))
        self.sport_button.setText(_translate("MainWindow", "Sport"))
        self.history_button.setText(_translate("MainWindow", "History"))
        self.literature_button.setText(_translate("MainWindow", "Literature"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow1()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
